In [28]:
import pandas as pd
import numpy as np
df = pd.read_csv("near_earth_asteroids_2025 (1).csv", low_memory=False)
print("Dataset loaded successfully")
print("Shape:", df.shape)

Dataset loaded successfully
Shape: (41281, 29)

In [29]:
print("first 5 rows are:")
print(df.head())
print("all the columns in the dataset are:")
print(df.columns)
print("to know about the data types:")
print(df.info())
print("to find any missing values are present:")
print(df.isnull().sum())

first 5 rows are:
      spkid                 full_name  pdes     name    pha      H  \
0  20000433        433 Eros (A898 PA)   433     Eros  False  10.39
1  20000719      719 Albert (A911 TB)   719   Albert  False  15.59
2  20000887      887 Alinda (A918 AA)   887   Alinda  False  13.82
3  20001036    1036 Ganymed (A924 UB)  1036  Ganymed  False   9.17
4  20001221      1221 Amor (1932 EA1)  1221     Amor  False  17.37

   diameter_km  diameter_m  diameter_is_estimated  \
0     16.84000     16840.0                  False
1      2.70683      2706.8                   True
2      4.20000      4200.0                  False
3     37.67500     37675.0                  False
4      1.00000      1000.0                  False

                  size_category  ...  per_y  moid_au     moid_km  \
0  Large (>1 km) — City killer+  ...   1.76   0.1480  22140485.0
1  Large (>1 km) — City killer+  ...   4.28   0.2010  30069172.0
2  Large (>1 km) — City killer+  ...   3.89   0.0797  11922950.0
3  Large (>1 km) — City killer+  ...   4.35   0.3430  51312070.0
4  Large (>1 km) — City killer+  ...   2.66   0.1080  16156570.0

   moid_lunar_distances       n  condition_code   first_obs    last_obs  \
0                 57.60  0.5598             0.0  1893-10-29  2021-05-13
1                 78.22  0.2302             0.0  1911-10-04  2026-03-20
2                 31.02  0.2533             0.0  1918-02-09  2025-08-27
3                133.49  0.2266             0.0  1924-10-23  2026-03-22
4                 42.03  0.3705             0.0  1932-03-12  2025-02-19

   data_arc  data_arc_years
0   46582.0          127.53
1   41806.0          114.46
2   39281.0          107.55
3   37040.0          101.41
4   33947.0           92.94

[5 rows x 29 columns]
all the columns in the dataset are:
Index(['spkid', 'full_name', 'pdes', 'name', 'pha', 'H', 'diameter_km',
       'diameter_m', 'diameter_is_estimated', 'size_category', 'albedo',
       'rot_per', 'class', 'e', 'a', 'i', 'q', 'ad', 'per', 'per_y', 'moid_au',
       'moid_km', 'moid_lunar_distances', 'n', 'condition_code', 'first_obs',
       'last_obs', 'data_arc', 'data_arc_years'],
      dtype='object')
to know about the data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41281 entries, 0 to 41280
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   spkid                  41281 non-null  int64
 1   full_name              41281 non-null  object
 2   pdes                   41281 non-null  object
 3   name                   182 non-null    object
 4   pha                    41281 non-null  bool
 5   H                      41279 non-null  float64
 6   diameter_km            41281 non-null  float64
 7   diameter_m             41281 non-null  float64
 8   diameter_is_estimated  41281 non-null  bool
 9   size_category          41281 non-null  object
 10  albedo                 1204 non-null   float64
 11  rot_per                2181 non-null   float64
 12  class                  41281 non-null  object
 13  e                      41281 non-null  float64
 14  a                      41281 non-null  float64
 15  i                      41281 non-null  float64
 16  q                      41281 non-null  float64
 17  ad                     41281 non-null  float64
 18  per                    41281 non-null  float64
 19  per_y                  41281 non-null  float64
 20  moid_au                41150 non-null  float64
 21  moid_km                41150 non-null  float64
 22  moid_lunar_distances   41150 non-null  float64
 23  n                      41281 non-null  float64
 24  condition_code         41279 non-null  float64
 25  first_obs              41280 non-null  object
 26  last_obs               41281 non-null  object
 27  data_arc               40875 non-null  float64
 28  data_arc_years         40875 non-null  float64
dtypes: bool(2), float64(19), int64(1), object(7)
memory usage: 8.6+ MB
None
to find any missing values are present:
spkid                        0
full_name                    0
pdes                         0
name                     41099
pha                          0
H                            2
diameter_km                  0
diameter_m                   0
diameter_is_estimated        0
size_category                0
albedo                   40077
rot_per                  39100
class                        0
e                            0
a                            0
i                            0
q                            0
ad                           0
per                          0
per_y                        0
moid_au                    131
moid_km                    131
moid_lunar_distances       131
n                            0
condition_code               2
first_obs                    1
last_obs                     0
data_arc                   406
data_arc_years             406
dtype: int64

**Check target column balance**

In [30]:
print(df["pha"].value_counts())
print("in percentage form:")
print(df["pha"].value_counts(normalize=True) * 100)

False    38742
True      2539
Name: pha, dtype: int64
in percentage form:
False    93.849471
True      6.150529
Name: pha, dtype: float64

**check the duplicates**

In [31]:
df.duplicated().sum()

0

In [32]:
# Create a copy of original dataset
df_model = df.copy()
# Drop columns that are not useful for first simple ML model
drop_columns = [
    "spkid",              
    "full_name",        
    "pdes",               
    "name",             
    "diameter_m",        
    "albedo",             
    "rot_per",          
    "first_obs",         
    "last_obs"           
]

df_model = df_model.drop(columns=drop_columns)

print("Shape after dropping columns:", df_model.shape)
df_model.head()

Shape after dropping columns: (41281, 20)

,pha,H,diameter_km,diameter_is_estimated,size_category,class,e,a,i,q,ad,per,per_y,moid_au,moid_km,moid_lunar_distances,n,condition_code,data_arc,data_arc_years
0,False,10.39,16.84000,False,Large (>1 km) — City killer+,AMO,0.2228,1.458,10.83,1.133,1.78,643.0,1.76,0.1480,22140485.0,57.60,0.5598,0.0,46582.0,127.53
1,False,15.59,2.70683,True,Large (>1 km) — City killer+,AMO,0.5466,2.637,11.57,1.195,4.08,1560.0,4.28,0.2010,30069172.0,78.22,0.2302,0.0,41806.0,114.46
2,False,13.82,4.20000,False,Large (>1 km) — City killer+,AMO,0.5712,2.474,9.40,1.061,3.89,1420.0,3.89,0.0797,11922950.0,31.02,0.2533,0.0,39281.0,107.55
3,False,9.17,37.67500,False,Large (>1 km) — City killer+,AMO,0.5332,2.665,26.68,1.244,4.09,1590.0,4.35,0.3430,51312070.0,133.49,0.2266,0.0,37040.0,101.41
4,False,17.37,1.00000,False,Large (>1 km) — City killer+,AMO,0.4346,1.920,11.87,1.085,2.75,972.0,2.66,0.1080,16156570.0,42.03,0.3705,0.0,33947.0,92.94

In [33]:
df_model.isnull().sum()

pha                        0
H                          2
diameter_km                0
diameter_is_estimated      0
size_category              0
class                      0
e                          0
a                          0
i                          0
q                          0
ad                         0
per                        0
per_y                      0
moid_au                  131
moid_km                  131
moid_lunar_distances     131
n                          0
condition_code             2
data_arc                 406
data_arc_years           406
dtype: int64

In [34]:
# Fill missing numerical values with median
missing_cols = ["H","moid_au","moid_km","moid_lunar_distances","condition_code","data_arc","data_arc_years"]
for col in missing_cols:
    df_model[col] = df_model[col].fillna(df_model[col].median())
print("Missing values after filling:")
print(df_model.isnull().sum())

Missing values after filling:
pha                      0
H                        0
diameter_km              0
diameter_is_estimated    0
size_category            0
class                    0
e                        0
a                        0
i                        0
q                        0
ad                       0
per                      0
per_y                    0
moid_au                  0
moid_km                  0
moid_lunar_distances     0
n                        0
condition_code           0
data_arc                 0
data_arc_years           0
dtype: int64

In [35]:
df_model.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41281 entries, 0 to 41280
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   pha                    41281 non-null  bool
 1   H                      41281 non-null  float64
 2   diameter_km            41281 non-null  float64
 3   diameter_is_estimated  41281 non-null  bool
 4   size_category          41281 non-null  object
 5   class                  41281 non-null  object
 6   e                      41281 non-null  float64
 7   a                      41281 non-null  float64
 8   i                      41281 non-null  float64
 9   q                      41281 non-null  float64
 10  ad                     41281 non-null  float64
 11  per                    41281 non-null  float64
 12  per_y                  41281 non-null  float64
 13  moid_au                41281 non-null  float64
 14  moid_km                41281 non-null  float64
 15  moid_lunar_distances   41281 non-null  float64
 16  n                      41281 non-null  float64
 17  condition_code         41281 non-null  float64
 18  data_arc               41281 non-null  float64
 19  data_arc_years         41281 non-null  float64
dtypes: bool(2), float64(16), object(2)
memory usage: 5.7+ MB

In [36]:
from sklearn.model_selection import train_test_split
# Convert target column from True/False to 1/0
df_model["pha"] = df_model["pha"].astype(int)

# Convert boolean feature to 1/0
df_model["diameter_is_estimated"] = df_model["diameter_is_estimated"].astype(int)

# One-hot encode categorical columns
df_encoded = pd.get_dummies(df_model, columns=["size_category", "class"], drop_first=True)

print("Shape after encoding:", df_encoded.shape)
df_encoded.head()

Shape after encoding: (41281, 24)

,pha,H,diameter_km,diameter_is_estimated,e,a,i,q,ad,per,...,n,condition_code,data_arc,data_arc_years,size_category_Medium (140m-1km) — Regional damage,size_category_Small (25-140m) — Local damage,size_category_Tiny (<25m) — Airburst/harmless,class_APO,class_ATE,class_IEO
0,0,10.39,16.84000,0,0.2228,1.458,10.83,1.133,1.78,643.0,...,0.5598,0.0,46582.0,127.53,0,0,0,0,0,0
1,0,15.59,2.70683,1,0.5466,2.637,11.57,1.195,4.08,1560.0,...,0.2302,0.0,41806.0,114.46,0,0,0,0,0,0
2,0,13.82,4.20000,0,0.5712,2.474,9.40,1.061,3.89,1420.0,...,0.2533,0.0,39281.0,107.55,0,0,0,0,0,0
3,0,9.17,37.67500,0,0.5332,2.665,26.68,1.244,4.09,1590.0,...,0.2266,0.0,37040.0,101.41,0,0,0,0,0,0
4,0,17.37,1.00000,0,0.4346,1.920,11.87,1.085,2.75,972.0,...,0.3705,0.0,33947.0,92.94,0,0,0,0,0,0

In [37]:
# Features and target
X = df_encoded.drop("pha", axis=1)
y = df_encoded["pha"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (41281, 23)
y shape: (41281,)

In [38]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

print("\nTraining target balance:")
print(y_train.value_counts(normalize=True) * 100)

print("\nTesting target balance:")
print(y_test.value_counts(normalize=True) * 100)

Training data shape: (33024, 23)
Testing data shape: (8257, 23)

Training target balance:
0    93.849927
1     6.150073
Name: pha, dtype: float64

Testing target balance:
0    93.847644
1     6.152356
Name: pha, dtype: float64

In [39]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score

# Create Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

# Train the model
rf_model.fit(X_train, y_train)

print("Random Forest model trained successfully")

Random Forest model trained successfully

In [40]:
# Predict on test data
y_pred = rf_model.predict(X_test)
# Predict probabilities for ROC-AUC
y_proba = rf_model.predict_proba(X_test)[:, 1]
print("Predictions completed")
accuracy = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_proba)
print("Accuracy:", accuracy)
print("ROC-AUC Score:", roc_auc)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Predictions completed
Accuracy: 0.9990311251059707
ROC-AUC Score: 0.999987552368962

Confusion Matrix:
[[7744    5]
 [   3  505]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7749
           1       0.99      0.99      0.99       508

    accuracy                           1.00      8257
   macro avg       0.99      1.00      1.00      8257
weighted avg       1.00      1.00      1.00      8257

In [41]:
import pandas as pd

feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf_model.feature_importances_
})

feature_importance = feature_importance.sort_values(by="Importance", ascending=False)

feature_importance.head(15)

                                              Feature  Importance
0                                                   H    0.181060
1                                         diameter_km    0.158497
10                                            moid_au    0.126699
11                                            moid_km    0.110814
17  size_category_Medium (140m-1km) — Regional damage    0.097835
12                               moid_lunar_distances    0.092764
15                                           data_arc    0.064757
16                                     data_arc_years    0.047236
14                                     condition_code    0.030168
6                                                   q    0.022186
18       size_category_Small (25-140m) — Local damage    0.021771
20                                          class_APO    0.011778
19      size_category_Tiny (<25m) — Airburst/harmless    0.010346
3                                                   e    0.007641
5                                                   i    0.003838

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score

# Create Logistic Regression pipeline with scaling
logistic_model = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        random_state=42
    ))
])

# Train the model
logistic_model.fit(X_train, y_train)

print("Logistic Regression model trained successfully")
# Predict on test data
y_pred_lr = logistic_model.predict(X_test)
y_proba_lr = logistic_model.predict_proba(X_test)[:, 1]

# Evaluate
accuracy_lr = accuracy_score(y_test, y_pred_lr)
roc_auc_lr = roc_auc_score(y_test, y_proba_lr)

print("Logistic Regression Accuracy:", accuracy_lr)
print("Logistic Regression ROC-AUC:", roc_auc_lr)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

print("\nClassification Report:")
print(classification_report(y_test, y_pred_lr))

Logistic Regression model trained successfully
Logistic Regression Accuracy: 0.9813491582899359
Logistic Regression ROC-AUC: 0.9986513372820267

Confusion Matrix:
[[7598  151]
 [   3  505]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99      7749
           1       0.77      0.99      0.87       508

    accuracy                           0.98      8257
   macro avg       0.88      0.99      0.93      8257
weighted avg       0.99      0.98      0.98      8257

In [44]:
comparison = pd.DataFrame({
    "Model": ["Random Forest", "Logistic Regression"],
    "Accuracy": [accuracy, accuracy_lr],
    "ROC_AUC": [roc_auc, roc_auc_lr]
})

comparison

                 Model  Accuracy   ROC_AUC
0        Random Forest  0.999031  0.999988
1  Logistic Regression  0.981349  0.998651

In [45]:
import joblib

# Save the final selected model
joblib.dump(rf_model, "nasa_neo_random_forest_model.pkl")

# Save the feature columns also
joblib.dump(list(X.columns), "nasa_neo_feature_columns.pkl")

print("Final Random Forest model saved successfully")
print("Feature columns saved successfully")

Final Random Forest model saved successfully
Feature columns saved successfully

In [46]:
df_encoded.to_csv("nasa_neo_cleaned_for_ml.csv", index=False)

print("Cleaned dataset saved successfully")
print("File name: nasa_neo_cleaned_for_ml.csv")

Cleaned dataset saved successfully
File name: nasa_neo_cleaned_for_ml.csv

In [5]:
import os
from azure.ai.ml import MLClient
from azure.identity import DefaultAzureCredential



ml_client = MLClient(
    DefaultAzureCredential(),
    subscription_id="42032ad4-24fc-45d8-adfe-bb741f014bc9",
    resource_group_name="deakinuni",
    workspace_name="Varsha-MLTASK"
)

Overriding of current TracerProvider is not allowed
Overriding of current LoggerProvider is not allowed
Overriding of current MeterProvider is not allowed
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented
Attempting to instrument while already instrumented

In [8]:
import os

os.makedirs("deployment", exist_ok=True)

In [6]:
from azure.ai.ml.entities import Model
model = Model(
    path="./nasa_neo_random_forest_model.pkl",   
    name="nasa-neo-model",
    description="Random Forest model for NASA asteroid hazard prediction",
    type="custom_model"
)

registered_model = ml_client.models.create_or_update(model)

print("Model registered successfully!")
print("Model name:", registered_model.name)

Uploading nasa_neo_random_forest_model.pkl (< 1 MB): 100%|██████████| 1.68M/1.68M [00:00<00:00, 24.3MB/s]

Model registered successfully!
Model name: nasa-neo-model

In [10]:
%%writefile deployment/score.py

import joblib
import json
import numpy as np
import pandas as pd

def init():
    global model
    model = joblib.load("model.pkl")

def run(raw_data):
    try:
        data = json.loads(raw_data)
        input_df = pd.DataFrame(data)
        prediction = model.predict(input_df)
        return prediction.tolist()
    except Exception as e:
        return str(e)

Overwriting deployment/score.py